# This CI will only work for trusted contributors. CI for public contributors
# runs via a webhook on the merge requests. There's nothing you have to do if
# you want your changes tested -- created pipelines will be automatically
# linked in the merge request and appropriate labels will be added to it.
# Changes to this file will NOT be reflected in the testing.

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

variables:
  git_url: ${CI_MERGE_REQUEST_PROJECT_URL}
  git_url_cache_owner: kernel
  branch: ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  commit_hash: ${CI_COMMIT_SHA}
  mr_id: ${CI_MERGE_REQUEST_IID}
  mr_url: ${CI_MERGE_REQUEST_PROJECT_URL}/-/merge_requests/${CI_MERGE_REQUEST_IID}
  title: ${CI_COMMIT_TITLE}
  kernel_type: internal
  make_target: rpm
  builder_image: quay.io/cki/builder-rhel8
  build_kabi_stablelist: 'true'
  tree_yaml_name: rhel
  publish_elsewhere: 'true'

realtime_check:
  variables:
    name: kernel-rt-rhel8
    merge_tree: ${CI_MERGE_REQUEST_PROJECT_URL}
    merge_tree_cache_owner: kernel
    merge_branch: main-rt
    architectures: 'x86_64'
    package_name: kernel-rt
    skip_test: 'true'
    skip_results: 'true'
  trigger:
    project: redhat/red-hat-ci-tools/kernel/cki-scratch-pipelines/scratch-pipelines
    branch: rhel8
    strategy: depend
  allow_failure: true

trigger_pipeline:
  variables:
    name: kernel-rhel8
    architectures: 'x86_64 ppc64le aarch64 s390x'
    kpet_tree_family: rhel8
    native_tools: 'true'
  trigger:
    project: redhat/red-hat-ci-tools/kernel/cki-scratch-pipelines/scratch-pipelines
    branch: rhel8
    strategy: depend
