RHEL_MAJOR = 8
RHEL_MINOR = 0

#
# RHEL_RELEASE
# -------------
#
# Represents build number in 'release' part of RPM's name-version-release.
#   name is <package_name>, e.g. kernel
#   version is upstream kernel version this kernel is based on, e.g. 4.18.0
#   release is <RHEL_RELEASE>.<dist_tag>[<buildid>], e.g. 100.el8
#
# Use this spot to avoid future merge conflicts.
# Do not trim this comment.
RHEL_RELEASE = 69
